table DimChannel
	lineageTag: bbca6542-f7e2-4719-8e0e-0ae1e0d3f1ca

	column ChannelKey
		dataType: int64
		formatString: 0
		lineageTag: c300fb94-2cba-4ba1-a652-8cd2c557c5f9
		summarizeBy: none
		sourceColumn: ChannelKey

		annotation SummarizationSetBy = Automatic

	column ChannelName
		dataType: string
		lineageTag: 6a982c7f-3e58-44c2-8edd-60ad0ea039ad
		summarizeBy: none
		sourceColumn: ChannelName

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	partition DimChannel-5a99d029-aa2d-4e89-bec6-42dbd8b66bf8 = m
		mode: import
		source =
				let
				    Source = Sql.Databases("MW-RSY-4KM1VQ3"),
				    ContosoRetailDW = Source{[Name="ContosoRetailDW"]}[Data],
				    dbo_DimChannel = ContosoRetailDW{[Schema="dbo",Item="DimChannel"]}[Data],
				    #"Removed Columns" = Table.RemoveColumns(dbo_DimChannel,{"ChannelLabel", "ChannelDescription", "ETLLoadID", "LoadDate", "UpdateDate", "FactSales", "FactSalesQuota"})
				in
				    #"Removed Columns"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

