table DimSalesTerritory
	lineageTag: e4b78743-71ec-4bda-a1a4-c73595693b6b

	column SalesTerritoryKey
		dataType: int64
		formatString: 0
		lineageTag: f3a9525b-e012-487e-af7e-0adcdf5c9ce8
		summarizeBy: count
		sourceColumn: SalesTerritoryKey

		annotation SummarizationSetBy = Automatic

	column GeographyKey
		dataType: int64
		formatString: 0
		lineageTag: 2967cef3-d46c-4e53-b383-2daa1301c792
		summarizeBy: none
		sourceColumn: GeographyKey

		annotation SummarizationSetBy = Automatic

	column SalesTerritoryName
		dataType: string
		lineageTag: d657704f-5405-4cf5-b6d2-ee37c4bc72fc
		summarizeBy: none
		sourceColumn: SalesTerritoryName

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column SalesTerritoryRegion
		dataType: string
		lineageTag: 36db2e32-2ddc-4a5f-a562-c2621dd30347
		summarizeBy: none
		sourceColumn: SalesTerritoryRegion

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column SalesTerritoryCountry
		dataType: string
		lineageTag: 02eaf965-8b83-456d-9383-a042c1f47a7c
		summarizeBy: none
		sourceColumn: SalesTerritoryCountry

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column SalesTerritoryGroup
		dataType: string
		lineageTag: 282987d6-178b-43e0-b68f-4ada2fa2a2c2
		summarizeBy: none
		sourceColumn: SalesTerritoryGroup

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	partition DimSalesTerritory-53af31e1-612e-4bd5-bbfb-bc00b6c80fce = m
		mode: import
		source =
				let
				    Source = Sql.Databases("MW-RSY-4KM1VQ3"),
				    ContosoRetailDW = Source{[Name="ContosoRetailDW"]}[Data],
				    dbo_DimSalesTerritory = ContosoRetailDW{[Schema="dbo",Item="DimSalesTerritory"]}[Data],
				    #"Removed Columns" = Table.RemoveColumns(dbo_DimSalesTerritory,{"Status", "ETLLoadID", "LoadDate", "UpdateDate", "DimGeography", "SalesTerritoryLabel", "SalesTerritoryLevel", "SalesTerritoryManager", "StartDate", "EndDate"})
				in
				    #"Removed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

